### ISSUE TITLE
JobActivator issue when Hangfire upgraded from 0.9.0 to 1.0.2

### ISSUE THREAD

**Issue by nnskumar** [odinserj/odinserj.net#2]
Hi,
I have upgraded the version to 1.0.2 and getting error when setting JobActivator.Current
the compiler error is "Cannot convert source type Hangfire.SimpleInjectorJobActivator to target type Hangfire.JobActivator". Could you please suggest (SimpleInjector code added below)

JobActivator.Current = new SimpleInjectorJobActivator(container);

 public class SimpleInjectorInitialize
    {
        /// <summary>

Initialize the container and register it as MVC and Web API Dependency Resolver.</summary>

        public static void Initialize()
        {
            var container = new Container();

```
        InitializeContainer(container);

        container.RegisterMvcControllers(Assembly.GetExecutingAssembly());
        container.RegisterWebApiControllers(GlobalConfiguration.Configuration);        

        container.Verify();

        //Set dependency resolver for MVC
        DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));

        //Set dependency resolver for Web API
        GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);

        //HangFire Initilisation
        JobActivator.Current = new SimpleInjectorJobActivator(container);
    }

    private static void InitializeContainer(Container container)
    {
        SimpleInjectorRegistration.RegisterServices(container);
        Service.SimpleInjectorRegistration.RegisterServices(container);
    }

}
```

**Comment by odinserj** [comment]
Unfortunately, `Hangfire.SimpleInjector` package does not support `Hangfire 1.0` package yet. I've created [this PR](https://github.com/devmondo/HangFire.SimpleInjector/pull/5) to add compatibility with the new Hangfire version. As a temporary workaround, you can uninstall this package and include the contents of https://github.com/devmondo/HangFire.SimpleInjector/blob/master/src/HangFire.SimpleInjector/SimpleInjectorJobActivator.cs to your project. Sorry for inconvenience :(
